# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    sudo apt-get update
    sudo apt-get install -y build-essential qt6-base-dev qt6-tools-dev
    cd src
    qmake6 PacketSender.pro
    make
    ls
  displayName: 'Build Packet Sender'

- script: |
    ls
    mkdir -p $(Build.ArtifactStagingDirectory)/bin
    cp packetsender $(Build.ArtifactStagingDirectory)/bin/
  displayName: 'Copy Packet Sender binary to staging'
